services:
  - type: web
    name: caresalesads
    runtime: python
    pythonVersion: 3.11.11
    buildCommand: |
      python -m venv venv && source venv/bin/activate && pip install -r requirements.txt
    startCommand: streamlit run app.py
    